DOMAIN = "twg"

CONF_DEVICE_ID = "device_id"
CONF_BASE_TOPIC = "base_topic"
CONF_OUT_COUNT = "out_count"

DEFAULT_BASE_TOPIC = "twg"
DEFAULT_OUT_COUNT = 8

TOPIC_STATE_SUFFIX = "dati"
TOPIC_COMMAND_SUFFIX = "comandi"
